// Historical background, teaching representations and modern explanations are labeled separately.
export const CHAPTER = Object.freeze({ id: 'chirality', title: '镜子里的两种分子：零度读数的秘密', minutes: '7—9 分钟', difficulty: '4/5 · 进阶' });
export const INITIAL_CHOICES = [
  'B 中的组成单位本来就不产生旋光。', '仪器或实验条件可能有问题。',
  'B 中可能有方向相反的作用，恰好抵消。', '信息还不够，我希望先获得更多证据。',
];
export const REFLECTION_CHOICES = ['正常的对照测量', '看见两类晶体', '分开溶解后的相反旋光', '重新混合回到零', '生物过程改变了剩余物', '我还保留疑问'];
export const CRYSTALS = ['left', 'right', 'right', 'left', 'right', 'left', 'left', 'right'];
// User-supplied narrative art: only create the image for the currently reached page.
export const ARTWORK = Object.freeze({
  zero: { file: 'chirality-ai-01-laboratory.png', alt: '旧式实验台上的两瓶透明样品、光学管和合起的研究笔记。' },
  sort: { file: 'chirality-ai-02-microscope.png', alt: '研究者在显微镜前观察，桌上放着晶体与镊子。' },
  'predict-separate': { file: 'chirality-ai-03-sealed-record.jpg', alt: '绳子系紧的实验记录仍未打开，旁边是样品瓶和空白卡片。' },
  'remix-result': { file: 'chirality-ai-04-recombination.jpg', alt: '两份透明溶液被倒入同一个容器，示意主动重新组合。' },
  reflect: { file: 'chirality-ai-05-reflection.jpg', alt: '翻开的空白调查笔记与铅笔，远处摆着样品瓶和光学管。' },
});
const option = (label, explanation) => ({ label, explanation });
export const QUESTIONS = [
  { id: 'models', skill: '设计能区分竞争解释的实验', prompt: '目前哪一步最可能区分“无效应”与“抵消”这两个模型？', answer: 1,
    hint: '好的检验要让两个解释对某种结果产生不同预期，而不仅仅让同一个数字更稳定。',
    reason: '先找到可分开的群体，再分别检验它们，才能让隐藏的贡献有机会单独显现。',
    options: [option('只把同一瓶 B 再测十次', '重复有助于估计随机误差，但两个模型都允许反复测到零，仍然无法区分。'), option('寻找能分开的不同群体，再分别测量', '分开以后，两种模型对各组可能有不同预期，因此这项调查有区分力。'), option('不分离成分，只把 B 整体浓缩', '如果相反贡献按同一比例增大，仍然抵消；无效应模型也仍预期为零。'), option('仅换用更亮的光源', '亮度可能改善读数质量，却没有改变两个模型的关键差别：样品内部是否有不同贡献。')] },
  { id: 'predict-separate', skill: '在结果揭示前作出模型预测', prompt: '如果抵消模型正确，两类晶体分别溶解后最值得期待什么？', answer: 2,
    hint: '把模型中的两类贡献分别单独保留下来，想想仪器各会收到什么；测量条件要匹配。',
    reason: '这是一项事先留下的预测，还需要打开实验记录接受检验。',
    options: [option('两份都继续接近零', '这更符合两组都没有可测旋光的情况，没有体现抵消模型中的两类非零贡献。'), option('只有一份旋光，另一份为零', '这样缺少与非零贡献相平衡的另一贡献，不能自然解释原先的零。'), option('两份旋光方向相反、大小相近', '在浓度、光程等条件匹配时，这正是两类相反贡献的可检验预测。'), option('两份都向同一方向旋光', '同方向的作用会叠加，不能按这个模型解释原先的抵消。'), option('晶体溶解后，这个问题就无法测量', '这里测量的就是溶液对光的作用。溶解还能检验差别是否依赖完整晶体。')] },
  { id: 'interpret', skill: '连接证据，同时限制结构推断', prompt: '这组分离后仍然相反的读数，目前最能支持什么？', answer: 0,
    hint: '分别问：原先的零怎样产生？完整晶体消失后，哪些差别还留着？',
    reason: '它支持抵消解释，也说明差异不能只归因于宏观晶体外形；完整的原子排列还没有因此确定。',
    options: [option('B 的零可由两个非零贡献抵消；差异不只来自整块晶体外形', '分离显出了相反作用，溶解后的差别又把解释推向更微观的层级。'), option('这证明原先仪器一定坏了', '正常对照不支持这个断言。原来的零可以是两个作用相抵后的真实总效果。'), option('光只是在完整晶体表面被扭转', '完整晶体已经溶解，表面已不在，溶液中的差别却保留下来。'), option('这已经给出了分子的全部三维结构', '实验约束了可能的解释，却没有直接显示全部原子的空间排列。')] },
  { id: 'predict-remix', skill: '把解释转化为干预预测', prompt: '如果抵消模型正确，匹配的两份样品重新混合后应读到什么？', answer: 3,
    hint: '把同时存在的两份贡献一起考虑，不要只看先倒入的那瓶。',
    reason: '两份作用在匹配条件下相抵，这是可以马上验证的预测。',
    options: [option('保留完整的正方向旋光', '这忽略了同时加入的相反贡献；两份的量与条件已经匹配。'), option('正方向、负方向随时间轮流出现', '仪器测的是同时存在的总作用。模型并没有预言它们轮流起效。'), option('出现比任一原液都更强的同方向旋光', '这是同向加强的预期，而刚才的证据显示两份作用方向相反。'), option('接近 0°', '匹配的相反贡献应使净作用接近零。下一页再检查实际记录。')] },
  { id: 'reconstruct', skill: '区分重复观察与因果重建', prompt: '为什么这比再测一次最初那瓶 B 更有说服力？', answer: 1,
    hint: '比较“再看同一瓶”与“改变组成，再检验预测”。证据强弱不取决于步骤多少。',
    reason: '分离、分别验证、主动重组把解释连成可检验的证据链，而不只是给零结果换一种说法。',
    options: [option('步骤越多，解释就一定越正确', '步骤多不保证证据强；关键是操作有没有检验模型特有的预测。'), option('验证隐藏贡献后，按预测主动重建了原现象', '我们先见到两个非零作用，再重建最初的零：解释指导的干预成功了。'), option('零读数本身就能证明有两类成分', '最初那个零恰好无法独自区分模型。说服力来自整条分离与重组链。'), option('从此所有零结果都能解释为抵消', '证据针对当前样品；别的零仍可能来自无效应、条件或测量灵敏度。')] },
  { id: 'biology', skill: '用有限证据提出有边界的解释', prompt: '这次生物观察最谨慎、最合理的解释是什么？', answer: 2,
    hint: '把结论限制在比较过的对象和过程内。“能区别”不等于普遍的好坏规则。',
    reason: '某些生物过程能够区分镜像形式；现代三维结构知识帮助解释这种选择性，不能无限外推。',
    options: [option('所有正旋光分子都有益，负旋光分子都有害', '实验比较的是消耗差异，不是健康作用。旋光方向不是有益或有害的标签。'), option('这证明 R 构型一定对应正旋光', 'R/S 与旋光方向是不同描述，这次实验没有建立两者的对应规则。'), option('某些生物过程能区分镜像分子，其三维结构可能参与这种区分', '证据支持这个体系中的选择性；具有空间结构的生物环境能使两种形式的相互作用不同。'), option('生命中的所有分子都只有一种手性', '一个体系的选择性不能证明全部生命分子的组成；也不是每个分子都有手性。'), option('组成相同，生物体系其实不可能区分', '三维匹配也影响相互作用。眼前的消耗差异正要求我们超越只比较组成。')] },
];
export const PAGES = [
  { id: 'zero', title: '两份相似样品，一个零', phase: '01 · 异常', label: '历史背景 · 教学示意', visual: 'instrument',
    paragraphs: ['十九世纪，两份样品在当时的化学分析和若干性质上十分相近。让平面偏振光穿过它们的溶液，差别却出现了。', 'A 使光的偏振方向明显转动；相同条件下，B 却接近 0°。仪器报告的是总效果——这个零，究竟说明什么？'],
    note: '光可以有确定的偏振方向，旋光仪比较穿过样品前后的方向。A/B 编号和图中读数是教学示意，不是历史原始数据。', clue: '相同测量条件下，A 有明显旋光，B 的总读数近零。' },
  { id: 'initial', title: '先留下你的解释', phase: '01 · 异常', label: '当前判断 · 不计分', visual: 'zero', interaction: 'initial',
    paragraphs: ['B 为什么是 0°？现在的信息还不足以选定唯一解释。选一个你目前更倾向的方向，也可以暂时跳过。'], note: '这不是猜历史。之后的证据可以改变判断；离开本页后，起点会保留，不能事后改写。' },
  { id: 'models', title: '让两个解释意见不同', phase: '02 · 竞争解释', label: '教学对照', visual: 'controls', quiz: 0,
    paragraphs: ['先核对浓度、光程、温度、光的波长和溶剂。空白接近零，已知旋光样品读数正常；B 重测仍接近零。', '模型 A「无效应」：组成单位本身不旋光。模型 B「抵消」：内部有正、负两类贡献，大小恰好相抵。两个模型现在都能解释零。'],
    note: '上述规范化对照用于教学；不能当成 Pasteur 某一天的实验日志。', clue: '正常空白与已知样品使简单仪器故障解释变弱，但重复的零仍不能区分两模型。' },
  { id: 'sort', title: '显微镜下，微小的一面', phase: '03 · 分离', label: '历史背景 · 分类示意', visual: 'crystals', interaction: 'sort',
    paragraphs: ['在适当结晶条件下，相关样品形成酒石酸钠铵盐晶体。一眼很像，放大后却看见：一处小晶面分别朝向镜像的两侧。', '按标出的小晶面把八颗示意晶体分为两组。先点击晶体，再选组；也可用 Tab 和 Enter。此活动不计分。'],
    note: '晶体固定朝向以便比较；这里的“左/右组”只是观察标签，不预先指定旋光正负。并非所有类似混合物都能这样手工分开。', clue: '晶体可按镜像小晶面的可见差别分为两群；这本身还不是旋光结论。' },
  { id: 'predict-separate', title: '先预测，再打开记录', phase: '03 · 分离', label: '教学实验 · 结果未揭示', visual: 'sealed-separate', quiz: 1,
    paragraphs: ['将两组晶体分别溶解，配成浓度匹配的溶液，使用相同光程、温度、波长和溶剂。', '实验记录尚未打开。请先让抵消模型给出一个可检验的预期。'] },
  { id: 'separate-result', title: '两边都不是零', phase: '04 · 证据', label: '依据历史实验改编', visual: 'separate', quiz: 2,
    paragraphs: ['记录打开：一份溶液产生正方向旋光，另一份产生大小相近的负方向旋光。', '完整晶体已经溶解，差别仍然存在。现在，我们比“看见两种外形”多知道了什么？'],
    note: '+α、−α 只表示匹配条件下相反的旋光，不是历史角度数据，也不把晶面左右直接等同于旋光方向。', clue: '分别溶解后，两份溶液旋光非零、方向相反；差异在晶体溶解后仍存在。' },
  { id: 'predict-remix', title: '能把那个零拼回来吗？', phase: '05 · 重建', label: '教学实验 · 结果未揭示', visual: 'sealed-remix', quiz: 3,
    paragraphs: ['这次主动改变样品组成：取浓度匹配、物质的量相当的两份相反旋光样品，重新混合。', '测量条件保持一致。读数仍封着；模型要先交出预测。'] },
  { id: 'remix-result', title: '零，被重新制造出来', phase: '05 · 重建', label: '依据历史实验改编', visual: 'remix', quiz: 4,
    paragraphs: ['记录打开，仪器回到接近 0°。分开时显出了两个非零作用，重新组合后，又重现最初的零。'],
    clue: '分离 → 相反的非零作用；等量重新组合 → 近零。模型经受了预测与重建。' },
  { id: 'microscopic', title: '不能停在晶体的外形', phase: '06 · 解释的尺度', label: '证据推理 · 概念示意', visual: 'dissolve',
    paragraphs: ['晶体溶解，原先完整的晶格不再保留，但两份溶液仍有相反旋光。', '关键的不对称性，需要追到比整块晶体更微观的组成层级。这支持一条研究方向，却不等于直接看到了完整的分子结构。'], note: '图中小单元是概念符号，不是显微镜拍到的分子。' },
  { id: 'modern', title: '今天，我们怎样称呼它', phase: '06 · 解释的尺度', label: '现代解释', visual: 'molecules',
    paragraphs: ['镜像却不能通过空间旋转重合，叫作「手性」。具有这种镜像关系的一对分子，叫作「对映体」。左右手可帮助想象，但手不是分子的真实形状。', '对映体在非手性环境中的许多物理化学性质相同或十分相近，旋光方向相反。等量的两种形式混合，称为外消旋混合物。'],
    detail: ['可选：别把几套名字混在一起', '(+)/(−) 是实验测得的旋光方向；R/S 是后来描述绝对空间构型的命名体系，两者没有简单的一一对应关系。D/L 也是另一套命名。本章的晶面左右标签不等同于任何一套分子命名。'] },
  { id: 'biology', title: '生命打破了平衡', phase: '07 · 第二次转折', label: '历史观察 · 改编示意', visual: 'biology', quiz: 5,
    paragraphs: ['后来，Pasteur 观察到：微生物作用于相关混合物后，两种镜像形式并没有被同样快地消耗。正旋光形式被优先消耗，剩余液出现负方向旋光。', '同样的混合物，遇到生物过程，抵消的平衡被改变了。'], note: '1857 年的微生物记录与 1860 年的特定霉菌示范应区分；此处不把它们拼成一次精确现场实验。', clue: '某些生物过程不等同地处理两个镜像形式，比例改变后，原来的旋光抵消被打破。' },
  { id: 'pocket', title: '环境也有自己的左右', phase: '07 · 第二次转折', label: '现代解释 · 匹配类比', visual: 'pocket',
    paragraphs: ['酶或受体的结合部位具有三维结构。当环境本身有手性时，两个镜像分子的接触与匹配可能不同，进而影响结合或转化。', '这不意味着一种一定是药，另一种一定是毒；作用取决于具体分子、具体生物环境和条件。'],
    note: '口袋图是三维匹配的简化类比，不是某种酒石酸酶的真实结构。', detail: ['历史后记', '1874 年，van ’t Hoff 和 Le Bel 提出了与碳原子三维排列有关的模型，使立体化学获得更明确的结构解释。不要把后来的完整理论放进 Pasteur 当年的认识中。'] },
  { id: 'reflect', title: '回看最初的那个零', phase: '08 · 调查记录', label: '事后回望 · 不计分', visual: 'notebook', interaction: 'reflect',
    paragraphs: ['哪条证据最改变你的判断？如果一开始就猜到了抵消，又是哪条证据让你真正愿意相信它，而不再只是猜测？'], note: '反思只保存在本机，可随调查笔记导出；不进入排行榜，不随成绩投稿。可以跳过。' },
  { id: 'conclusion', title: '零结果，不是调查的句号', phase: '08 · 调查记录', label: '本次调查的结论', visual: 'chain',
    paragraphs: ['零结果并不自动意味着什么都没有。提出竞争解释，让它们给出不同预测，再通过分离与重组检验，才让这个零变得可以理解。', '这条证据链支持当前样品的抵消模型。其他零结果仍可能来自没有效应、测量条件或灵敏度，需要各自调查。'] },
];
export const SOURCES = [
  ['Institut Pasteur · Early years (1847–1862)', 'https://www.pasteur.fr/en/about-us/early-years-1847-1862'],
  ['RSC · Introduction and Historical Background', 'https://books.rsc.org/books/monograph/2020/chapter/4606917/Introduction-and-Historical-Background'],
  ['Flack (2009) · Louis Pasteur’s discovery of molecular chirality', 'https://crystal.flack.ch/dox/sh5092.pdf'],
  ['Gál (2008) · Pasteur and biological enantioselectivity', 'https://doi.org/10.1002/chir.20494'],
  ['Science History Institute · Pasteur 晶体学手稿', 'https://digital.sciencehistory.org/works/d791sg21k'],
];
